server.port=8085

# Ensure the complete parameters are chained properly at the end of the URL
spring.datasource.url=jdbc:mysql://localhost:3306/springrestlearn?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Navya@1705

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true